---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  GMAP_TOKEN: googlemap_api_key
  OPENAI_API_KEY: openai_api_key
  REDIS_URL: redis://
  # Application
  SESSION_SECRET: <some secret>

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  GMAP_TOKEN: googlemap_api_key
  OPENAI_API_KEY: openai_api_key
  REDIS_URL: redis://

  # Application
  SESSION_SECRET: <some secret>

production:
  # Infrastructure
  GMAP_TOKEN: googlemap_api_key
  REDIS_URL: redis://

  # Application
  SESSION_SECRET: <some secret>