---
# Name your file secrets.yml

development:
  # Infrastructure
  API_HOST: http://localhost:9090/api/v1
  DB_FILENAME: db/local/dev.db
  GMAP_TOKEN: googlemap_api_key
  OPENAI_API_KEY: openai_api_key
  REDIS_URL: redis://
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  RECOMMENDATION_QUEUE: travelroute-recommendation-development
  RECOMMENDATION_QUEUE_URL: <set by AWS>
  # Application
  SESSION_SECRET: <some secret>

test:
  # Infrastructure
  API_HOST: http://localhost:9090/api/v1
  DB_FILENAME: db/local/test.db
  GMAP_TOKEN: googlemap_api_key
  OPENAI_API_KEY: openai_api_key
  REDIS_URL: redis://
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  RECOMMENDATION_QUEUE: travelroute-recommendation-development
  RECOMMENDATION_QUEUE_URL: <set by AWS>

  # Application
  SESSION_SECRET: <some secret>

production:
  # Infrastructure
  API_HOST: http://localhost:9090/api/v1
  DB_FILENAME: db/local/test.db
  GMAP_TOKEN: googlemap_api_key
  OPENAI_API_KEY: openai_api_key
  REDIS_URL: redis://
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  RECOMMENDATION_QUEUE: travelroute-recommendation-development
  RECOMMENDATION_QUEUE_URL: <set by AWS>

  # Application
  SESSION_SECRET: <some secret>